// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4T5UrtDR_thns8OR1f97gZmuLfWwKytU',
    appId: '1:118541019694:web:a65cb6957673b1c6028dbf',
    messagingSenderId: '118541019694',
    projectId: 'william-bfd84',
    authDomain: 'william-bfd84.firebaseapp.com',
    storageBucket: 'william-bfd84.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5CXquVmfqPlD3516NW2-WXucJcVA0ypo',
    appId: '1:118541019694:android:0ccbb4623b4bd096028dbf',
    messagingSenderId: '118541019694',
    projectId: 'william-bfd84',
    storageBucket: 'william-bfd84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUr-kETAs1wIRtIy3py8aA0xiF5-DdxNs',
    appId: '1:118541019694:ios:8bb14768db9f4fcf028dbf',
    messagingSenderId: '118541019694',
    projectId: 'william-bfd84',
    storageBucket: 'william-bfd84.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUr-kETAs1wIRtIy3py8aA0xiF5-DdxNs',
    appId: '1:118541019694:ios:8bb14768db9f4fcf028dbf',
    messagingSenderId: '118541019694',
    projectId: 'william-bfd84',
    storageBucket: 'william-bfd84.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4T5UrtDR_thns8OR1f97gZmuLfWwKytU',
    appId: '1:118541019694:web:c91b5182be6dbfed028dbf',
    messagingSenderId: '118541019694',
    projectId: 'william-bfd84',
    authDomain: 'william-bfd84.firebaseapp.com',
    storageBucket: 'william-bfd84.firebasestorage.app',
  );

}